services:
  - type: web
    name: suna-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: suna-postgres
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: suna-redis
          property: connectionString
    healthCheckPath: /health

  - type: web
    name: suna-frontend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: suna-backend
          property: host

databases:
  - name: suna-postgres
    databaseName: suna
    user: suna_user
    plan: free

  - name: suna-redis
    plan: free
